apiVersion: v1
kind: Service
metadata:
  name: safety-net-backend-service

spec:
  selector:
    app: safety-net-backend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: ClusterIP
  